const sections=[['start','Start here'],['themes','Themes & ideas'],['craft','Bring writing to life'],['speech','Direct speech lab'],['verbs','Saying verbs'],['plot','Complications & turning points'],['viewpoint','A different viewpoint'],['flashback','Flashbacks'],['conclusions','Conclusions'],['check','Final checks']];
const main=document.querySelector('#main');
document.querySelector('#nav').innerHTML=sections.map(([id,title],i)=>`<a href="#${id}" data-section="${id}"><span class="num">${String(i+1).padStart(2,'0')}</span>${title}</a>`).join('');
document.querySelector('#print').onclick=()=>window.print();
document.querySelector('.skip').onclick=e=>{e.preventDefault();main.focus();main.scrollIntoView({block:'start'});};
function start(){return `<p class="eyebrow">YOUR FINAL REVISION STOP</p><h1>Make every word work.</h1><p class="lead">Revisit familiar stories and the writing moves you have learnt. Explore the examples, then check the details that make your writing clear.</p><div class="hero"><div><p class="eyebrow">START WITH A COMMON STUMBLING BLOCK</p><h2>Who said it?<br>Where does the comma go?</h2><p>Build and repair direct speech, one decision at a time.</p><a class="primary" href="#speech">Open the direct speech lab</a></div><img class="hero-illustration" src="writing-doodles.png" alt="Playful doodles of a pen, notebook, speech bubble and idea bulb"></div><h2>Choose what you need today</h2><div class="grid three">${[['themes','01 · IDEAS','Find your story','Responsibility, courage, kindness and the unexpected.'],['craft','02 · WRITER’S TOOLS','Let the reader feel it','Sensory details, characterisation and exploding a moment.'],['speech','03 · DIALOGUE','Punctuate direct speech','Speech tags, commas and new speaker paragraphs.'],['verbs','04 · WORD CHOICE','Find a saying verb','Choose verbs by emotion and meaning.'],['plot','05 · STORY SHAPE','Make change believable','Complications, dilemmas and turning points.'],['viewpoint','06 · VOICE','See it differently','Try an animal, an adult, an elderly person or a younger child.'],['flashback','07 · ORGANISATION','Move through time','Enter a memory clearly and return with purpose.'],['conclusions','08 · ENDINGS','Finish with purpose','Explore six ways to end a story.'],['check','09 · CONVENTIONS','Give it a final check','Your classroom expectations in one place.']].map(([id,label,title,text])=>`<a class="card card-link" href="#${id}"><span class="label">${label}</span><h3>${title}</h3><p>${text}</p></a>`).join('')}</div><div class="notice lime"><b>Remember:</b> use techniques to develop the topic. You do not need every technique in every composition.</div>`;}
const state={theme:0,craft:'senses',emotion:0,sense:0,speech:'rules',verb:0,plot:0,pov:0,flash:0,ending:0,endingTheme:0,rep:0,answers:{},drafts:{},checks:new Set(),builder:{speaker:'Tom',position:'back',kind:'statement',style:'both'}};
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const example=(text,cls='')=>`<div class="example ${cls}">${esc(text)}</div>`;
const note=(text)=>`<div class="notice">${text}</div>`;
const head=(k,t,d)=>`<p class="eyebrow">${k}</p><h1>${t}</h1><p class="lead">${d}</p>`;
const tabs=(items,key)=>`<div class="tabs" role="group" aria-label="Choose ${key}">${items.map(([id,title])=>`<button class="pill" data-pick="${key}" data-value="${id}" aria-pressed="${String(state[key])===String(id)}">${esc(title)}</button>`).join('')}</div>`;
const reveal=(title,body)=>`<details><summary>${title}</summary><div>${body}</div></details>`;
function scratch(){return ''; }
const singleQuizzes={
 sensory:{q:'Which detail best develops Tom’s anxiety during the examination?',options:['The classroom had four white walls.','Tom rubbed his damp palms against his shorts before turning the page.','The delicious smell of lunch filled his dreams.'],a:1,why:'The physical sensation connects to the action and the pressure Tom feels. Details should serve this moment.'},
 show:{q:'Which sentence shows a character’s guilt through a meaningful action?',options:['He was extremely guilty and very remorseful.','His face was red, white, purple and green.','Tom slid the copied answers beneath his book when Mother entered.'],a:2,why:'The attempt to conceal his work gives the reader a clue to his guilt. The action is connected to the cause.'},
 explode:{q:'Which moment deserves the most space in Tom’s honesty story?',options:['The moment he chooses between another lie and a confession.','Every step of his journey to school.','A list of everything in his pencil case.'],a:0,why:'His decision carries the theme. Slow down where the choice and its consequences matter.'},
 turning:{q:'Which option is a turning point in an unexpected-friendship story?',options:['The afternoon became warmer.','Jayden saw Ethan shielding the frightened cat and realised he had misjudged him.','The school bell rang at the usual time.'],a:1,why:'New evidence changes Jayden’s understanding. The next action can grow from that change.'},
 character:{q:'Which action most convincingly proves that Zack has changed?',options:['He announces that he is now a perfect person.','He receives a prize for saying sorry.','He refuses a chance to cut the queue and helps a pupil collect dropped coins.'],a:2,why:'A similar temptation returns. His different response demonstrates change.'},
 pov:{q:'The story uses the cat’s limited viewpoint. Which sentence fits?',options:['The boy’s examination would begin at eight the next morning.','A bowl scraped across the ground. I sniffed the air and crept closer.','The boy knew that compassion was a valuable moral quality.'],a:1,why:'The cat notices sound, smell and movement. The other options give it unexplained knowledge of human schedules or thoughts.'},
 flash:{q:'Which ending returns clearly from a past memory to the current scene?',options:['Then many other things had happened before that.','I suddenly woke up and it was all a dream.','“Your turn,” Ryan called. I looked up and stepped onto the pitch.'],a:2,why:'A voice in the current scene anchors the return. The narrator then acts in the present story frame.'}
};
function quiz(id,q){if(!id.startsWith('speech-'))return '';const selected=state.answers[id];return `<div class="quiz" data-quiz="${id}"><span class="label blue">QUICK CHECK</span><h3>${esc(q.q)}</h3><div class="options">${q.options.map((o,i)=>`<button class="option ${selected===i?(i===q.a?'correct':'wrong'):''}" data-answer="${id}" data-choice="${i}" aria-pressed="${selected===i}">${esc(o)}</button>`).join('')}</div><div class="feedback ${selected===undefined?'':selected===q.a?'good':'bad'}" role="status">${selected===undefined?'':`<b>${selected===q.a?'Yes — that works.':'Look again.'}</b> ${esc(selected===q.a?q.why:'Read the rule and try another choice.')} `}</div></div>`;}
function themes(){const t=STUDIO.themes[state.theme];return head('01 · THEMES & IDEAS','Find the heart of your story.','Start with the exact topic. Choose events that make its meaning clear.')+tabs(STUDIO.themes.map((x,i)=>[i,x.title]),'theme')+`<div class="card"><span class="label lime">${t.tag}</span><h2>${t.title}</h2><p><b>Ask yourself:</b> ${t.question}</p><h3>${t.story}</h3><ol class="steps"><li><b>Before:</b> ${t.before}</li><li><b>Turning point:</b> ${t.turn}</li><li><b>After:</b> ${t.after}</li></ol></div><h2>Change the topic. Change the focus.</h2><div class="grid">${t.adapt.map(([a,b])=>`<div class="card"><h3>${a}</h3><p>${b}</p></div>`).join('')}</div>${note(`<b>Avoid this trap:</b> ${t.trap}`)}${scratch('theme-'+state.theme,t.prompt,'')}${reveal('A five-point planning check','<ol><li>What does the main character want?</li><li>What gets in the way?</li><li>What important choice or discovery changes things?</li><li>What happens because of that choice?</li><li>How does the ending answer the topic?</li></ol>')}<p class="caption">These are revision families, not predictions of the next examination topic. Adapt a familiar idea; do not force a memorised story onto an unsuitable topic or picture.</p>`;}
function craft(){return head('02 · WRITER’S TOOLS','Bring the moment to life.','Choose details that reveal the setting, the feeling or the character’s next decision.')+tabs([['senses','The five senses'],['show','Show, don’t tell'],['explode','Explode the moment'],['turning','Turning points'],['character','Characterisation']],'craft')+craftBody();}
function craftBody(){
if(state.craft==='senses'){const [name,question,text,why]=STUDIO.senses[state.sense];return `<h2>The five senses</h2><p>Choose two or three relevant details. You do not need all five senses in every scene.</p>${tabs(STUDIO.senses.map((x,i)=>[i,x[0]]),'sense')}<div class="card"><span class="label">${name.toUpperCase()}</span><h3>${question}</h3>${example(text)}<p>${why}</p></div>${note('<b>Keep it natural:</b> in your sports notes, a clear choice was “A sharp blast of the whistle signalled the start of the match.” A useful detail does not need a dramatic comparison.')}${quiz('sensory',singleQuizzes.sensory)}${scratch('sensory','Write two connected sensory details for a busy canteen, a rainy pavement or a tense match.','Coins clinked against the counter as Zack joined the queue. The aroma of fried noodles drifted towards him, and he looked impatiently at the pupils ahead.')}`;}
if(state.craft==='show'){const [feeling,tell,show,why]=STUDIO.emotions[state.emotion];return `<h2>Let the reader notice the clues</h2><p>Use the character’s <b>face, body, actions, thoughts or voice</b>. Select clues that suit this person and this situation.</p>${tabs(STUDIO.emotions.map((x,i)=>[i,x[0]]),'emotion')}<div class="comparison"><div class="card"><span class="label">❌ 🙁 TELL</span>${example(tell,'plain')}</div><div class="card"><span class="label lime">✅ 😊 SHOW</span>${example(show)}<p class="caption">${why}</p></div></div>${note('<b>Show the important moments.</b> Brief telling is useful for moving between scenes. Avoid filling every sentence with body reactions, similes and feeling words.')}${quiz('show',singleQuizzes.show)}${scratch('show-'+state.emotion,`Show ${feeling.toLowerCase()} using two connected clues. Give the feeling a clear cause.`,'')}`;}
if(state.craft==='explode'){return `<h2>Make a few seconds matter</h2><p>Slow down one important moment. Break it into small actions and let the reader experience the character’s hesitation.</p><div class="comparison"><div class="card"><span class="label">❌ 🙁 RUSHED</span>${example('Tom was caught and confessed.','plain')}</div><div class="card"><span class="label lime">✅ 😊 DEVELOPED</span>${example('Tom stared at the matching error. His thumb pressed against the edge of the paper. He could still call it a coincidence.\n\nThen he noticed Mother’s note beneath his pencil case.\n\nHe swallowed.\n\n“I copied John’s work,” he admitted.')}<p class="caption">Small action → thought → meaningful detail → choice.</p></div></div><ol class="steps"><li><b>Freeze:</b> where is the character, and what is about to happen?</li><li><b>Zoom in:</b> select a hand movement, sound, object or expression.</li><li><b>Enter the thought:</b> what does the character fear, want or consider?</li><li><b>Release:</b> show the decision and move the story forward.</li></ol>${note('<b>Control the pace:</b> mix short and longer sentences. Do not add a separate paragraph for every ordinary action or describe the same feeling five times.')}${quiz('explode',singleQuizzes.explode)}${scratch('explode','Explode this moment in four to six sentences: Marcus is about to blame Zane when he notices Zane’s completed work.','Marcus drew breath to complain. Then a row of finished drawings appeared on the screen. He looked at Zane, whose hand was still resting on the mouse. Had he been wrong all along? Marcus loosened his grip on the laptop. “Show me what you have done,” he said.')}`;}
if(state.craft==='turning'){return `<h2>Something changes — and the story follows</h2><p>A turning point changes a decision, understanding or relationship. It may happen during the climax, but it does not have to be the loudest event.</p><div class="grid"><div class="card"><h3>Tom: a decision</h3><p><b>Before:</b> he looks for an excuse.</p><p><b>Trigger:</b> Mother’s note reminds him of her trust.</p><p><b>After:</b> he confesses and accepts the consequences.</p></div><div class="card"><h3>Jayden: a new understanding</h3><p><b>Before:</b> he dismisses Ethan as unfriendly.</p><p><b>Trigger:</b> he sees Ethan caring for the cat.</p><p><b>After:</b> he offers help and begins a conversation.</p></div></div>${note('<b>Test your turning point:</b> “Because the character noticed / realised / decided ___, the character then ___.” If the next action is unchanged, you may have added an event without a real turn.')}${quiz('turning',singleQuizzes.turning)}${scratch('turning','Complete the cause-and-effect sentence for your own story.','Because Zack saw Ravi struggling not to cry, he stopped defending himself and offered to replace the meal.')}`;}
return `<h2>Reveal the person through the story</h2><p>Characterisation helps the reader understand what a character is like. Show a pattern, then test it under pressure.</p><div class="grid">${[
['Actions & habits','Zack edged towards the front whenever he thought nobody was watching.','Repeated behaviour reveals impatience.'],
['Dialogue & manner','“You can find the pictures,” Marcus said curtly, pulling the laptop towards himself.','His words and action show that he does not trust Zane with an important role.'],
['Thoughts & motives','Tom imagined Mother’s tired eyes after another evening of helping him.','His worry explains why the examination matters to him.'],
['Appearance in context','Mr Tan stood at the gate with our football tucked firmly beneath one arm.','A chosen posture or object can reveal more than a list of facial features.'],
['Other people’s reactions','When Zack approached the queue, Jason moved his tray closer and watched him.','A reaction suggests a history between characters.'],
['Choices & change','Zack saw the gap beside his friends, then walked to the back of the queue.','A new response to an old temptation proves growth.']
].map(([t,e,w])=>`<div class="card"><h3>${t}</h3>${example(e)}<p class="caption">${w}</p></div>`).join('')}</div>${note('<b>Avoid instant labels:</b> let an older person have strengths, a quiet pupil have useful ideas, and a joker be dependable. A nickname such as “Bulldozer” works only when behaviour gives it meaning.')}${quiz('character',singleQuizzes.character)}`;
}
function speech(){return head('03 · DIRECT SPEECH LAB','Make your dialogue clear.','Practise the punctuation first. Then choose words and actions that reveal the speaker.')+tabs([['rules','Learn the patterns'],['build','Build a sentence'],['quiz','Choose & check'],['repair','Repair the errors'],['paragraph','New speaker, new paragraph']],'speech')+speechBody();}
function speechBody(){
 if(state.speech==='rules')return `<div class="rule-grid">${STUDIO.speechRules.map(([t,e,d])=>`<div class="card"><h3>${t}</h3>${example(e)}<p>${d}</p></div>`).join('')}</div>${note('<b>Speech tag or action?</b> Said, asked and whispered tell us how words are spoken. Smiled, nodded, pointed and shrugged describe actions. Write “I agree,” she said, nodding. The action adds detail to the tag.')}<div class="actions"><button class="primary" data-pick="speech" data-value="quiz">Check your understanding</button></div>`;
 if(state.speech==='build')return `<h2>Choose a pattern and watch the punctuation</h2><div class="card"><div class="controls">${selectField('speaker','Who is speaking?',[['Tom','Tom'],['he','he'],['Ethan','Ethan'],['she','she'],['I','I']])}${selectField('position','Where is the tag?',[['back','After the speech'],['front','Before the speech']])}${selectField('kind','What kind of speech?',[['statement','A statement'],['question','A question'],['exclamation','An exclamation']])}${selectField('style','Add detail',[['plain','Speech tag only'],['adverb','An adverb'],['action','An accompanying action'],['both','An adverb and an action']])}</div><div id="builder-result" aria-live="polite">${builderOutput()}</div></div>${note('<b>Choose detail for a reason.</b> An adverb explains how the words are spoken. An action can reveal hesitation, emotion or intention. You do not need both every time. Avoid repetition such as “whispered quietly” when the adverb adds nothing.')}<h2>Two tagged ways to add an action</h2><div class="comparison"><div class="card"><h3>Tag at the back ✅😊</h3>${example('“I am sorry,” Tom said, lowering his eyes.')}<p>Said is the tag; lowering his eyes adds the action.</p></div><div class="card"><h3>Tag at the front ✅😊</h3>${example('Tom lowered his eyes and said, “I am sorry.”')}<p>The action comes first, but said still tags the speech.</p></div></div>`;
 if(state.speech==='quiz')return `<div class="lesson-head"><h2>Choose the version that works</h2><span class="score" id="speech-score">${speechScore()}</span></div><p>Each question explains the rule after a correct choice. You can retry a choice.</p>${STUDIO.speechQuiz.map((q,i)=>quiz('speech-'+i,q)).join('')}<button class="secondary" id="reset-quiz">Reset these questions</button>`;
 if(state.speech==='repair'){const r=STUDIO.repairs[state.rep];return `<h2>Be the editor</h2>${tabs(STUDIO.repairs.map((_,i)=>[i,`Repair ${i+1}`]),'rep')}<div class="card"><p>Rewrite this sentence with correct punctuation and capital letters.</p>${example(r.raw,'plain')}<label for="repair-input">Your corrected sentence</label><textarea id="repair-input" data-draft="repair-${state.rep}">${esc(state.drafts['repair-'+state.rep]||'')}</textarea><div class="actions"><button class="primary" id="check-repair">Check my repair</button><button class="secondary" id="show-repair">Show a suggested repair</button></div><div id="repair-feedback" class="feedback" role="status"></div><p class="caption">Straight and curly speech marks are both accepted. The checker recognises the suggested repairs; another grammatical rewrite may also work.</p></div>`;}
 return `<h2>Let the reader follow the conversation</h2><p><b>Begin a new paragraph each time a different person speaks.</b> Keep a speaker’s related action beside that speaker’s words.</p><div class="comparison"><div class="card"><span class="label">❌ 🙁 HARD TO FOLLOW</span>${example('“I cannot fix it,” Marcus said. Zane reached for the laptop. “Let me try,” he replied. “You know how?” Marcus asked.','plain')}</div><div class="card"><span class="label lime">✅ 😊 CLEAR SPEAKER CHANGES</span><div class="example quote-lines"><p>“I cannot fix it,” Marcus said.</p><p>Zane reached for the laptop. “Let me try,” he replied.</p><p>“You know how?” Marcus asked.</p></div></div></div><div class="quiz"><h3>How many speaker paragraphs does this exchange need?</h3><div class="options"><button class="option" data-paragraph="2">Two: there are two characters.</button><button class="option" data-paragraph="3">Three: Marcus → Zane → Marcus.</button><button class="option" data-paragraph="1">One: they are discussing the same problem.</button></div><div id="paragraph-feedback" class="feedback" role="status"></div></div>${note('<b>Names keep the speaker clear.</b> If two boys are speaking, repeated he said tags may confuse the reader. Use the name when the pronoun could refer to either person.')}<h2>One speaker can say more than one sentence</h2>${example('“I saved a copy,” Zane said, opening a folder. “We can use it to restore the missing slides,” he added.')}<p>There is no need to start a new paragraph between these two spoken sentences: the speaker has not changed.</p>`;
}
function selectField(key,label,values){return `<div class="field"><label for="build-${key}">${label}</label><select id="build-${key}" data-builder="${key}">${values.map(([v,t])=>`<option value="${v}" ${state.builder[key]===v?'selected':''}>${t}</option>`).join('')}</select></div>`;}
function makeSpeech(b){const s=b.speaker,front=s[0].toUpperCase()+s.slice(1);const values={statement:['I can help','said','calmly','placing the bag on the table'],question:['May I help you','asked','gently','holding out a hand'],exclamation:['Look out','shouted','urgently','pointing towards the fallen branch']};const [words,verb,adverb,action]=values[b.kind];const hasAdverb=['adverb','both'].includes(b.style),hasAction=['action','both'].includes(b.style);const tag=verb+(hasAdverb?' '+adverb:'');const end=b.kind==='question'?'?':b.kind==='exclamation'?'!':b.position==='back'?',':'.';if(b.position==='front')return (hasAction?action[0].toUpperCase()+action.slice(1)+', '+s:front)+' '+tag+', “'+words+end+'”';return '“'+words+end+'” '+s+' '+tag+(hasAction?', '+action:'')+'.';}
function builderOutput(){const b=state.builder;const rule=b.position==='front'?'The tag comes first. The comma after the saying verb or adverb introduces the speech.':b.kind==='statement'?'The comma stays inside the speech marks. The tag continues the sentence.':'The question mark or exclamation mark stays inside the speech marks. Do not add a comma after it.';return `<h3 style="margin-top:24px">Your sentence</h3>${example(makeSpeech(b))}<p class="caption">${rule} ${['he','she'].includes(b.speaker)?(b.position==='back'||['action','both'].includes(b.style)?'The pronoun stays lower case because it does not begin the sentence.':'The pronoun has a capital letter because it begins the sentence.'):b.speaker==='I'?'The pronoun I is always capitalised.':'A person’s name keeps its capital letter.'}</p>`;}
function speechScore(){return `${STUDIO.speechQuiz.filter((q,i)=>state.answers['speech-'+i]===q.a).length} / ${STUDIO.speechQuiz.length} correct`}
function plot(){const p=STUDIO.plots[state.plot];return head('05 · COMPLICATIONS & TURNING POINTS','Give the story a reason to change.','A complication gets in the way of what the character wants. Develop the response and the consequences.')+tabs(STUDIO.plots.map((p,i)=>[i,p.name]),'plot')+`<div class="card"><span class="label blue">${p.kind.toUpperCase()}</span><h2>${p.name}</h2><ol class="steps"><li><b>Trigger:</b> ${p.spark}</li><li><b>Build the pressure:</b> ${p.build}</li><li><b>Slow the moment:</b> ${p.moment}</li><li><b>Choice:</b> ${p.choice}</li><li><b>Consequence:</b> ${p.after}</li></ol></div>${note(`<b>Keep it believable:</b> ${p.avoid}`)}${(state.plot===2||state.plot===3)?dilemmaPanel(state.plot===3?'moral':'ordinary'):''}${scratch('plot-'+state.plot,p.question,'')}<h2>A useful distinction</h2><div class="grid"><div class="card"><h3>Dilemma</h3><p>Two choices both involve a cost. A schedule clash can create a dilemma even when neither option is dishonest.</p></div><div class="card"><h3>Moral dilemma</h3><p>The choice involves values, duty or right and wrong. A desire to protect a friend may conflict with fairness to someone wrongly blamed.</p></div></div>${note('<b>Link back to the topic.</b> A fire, quarrel or fight is not automatically the main point. Ask what the incident reveals about responsibility, courage, kindness or another required theme.')}`;}
function dilemmaPanel(kind){const d=STUDIO.dilemmaNotes[kind];return `<h2>Explore ${kind==='moral'?'a moral dilemma':'a dilemma'}</h2><div class="grid"><div class="card"><h3>Choice A</h3><p>${d.choices[0]}</p></div><div class="card"><h3>Choice B</h3><p>${d.choices[1]}</p></div></div><p class="notice lime"><b>Remember:</b> ${d.detail}</p><div class="comparison"><div class="card weak-card"><span class="label">❌ 🙁 TOO QUICK</span>${example(d.weak,'plain')}<p>The reader cannot feel the pressure or see why the choice matters.</p></div><div class="card good-card"><span class="label lime">✅ 😊 DEVELOPED</span>${example(d.strong)}<p>Choices, consequences, hesitation and the decision are visible.</p></div></div><h2>Explode the moment</h2><p>The decision may take one sentence. Give the struggle before it a full paragraph when it carries the story.</p><ol class="steps">${STUDIO.dilemmaNotes.craft.map(x=>`<li>${x}</li>`).join('')}</ol>${kind==='moral'?`<div class="grid"><div class="card"><h3>Tom and the examination</h3>${example(STUDIO.dilemmaNotes.tom)}</div><div class="card"><h3>The lost wallet</h3>${example(STUDIO.dilemmaNotes.wallet)}</div></div>`:''}<p class="caption">Inspired by Ms H’s moral-dilemma notes. Choose details that suit your own character; do not memorise the models.</p>`;}
function verbs(){const v=STUDIO.verbs[state.verb];return head('04 · SAYING VERBS','Find the right saying verb.','Choose a verb because its meaning fits the speaker’s emotion and intention.')+`<p>Said is often useful. These alternatives add a more specific meaning when the moment calls for it.</p>${tabs(STUDIO.verbs.map((v,i)=>[i,v.name]),'verb')}<div class="card"><h2>${v.name}</h2><div class="word-bank">${v.words.map(w=>`<span class="word">${w}</span>`).join('')}</div><span class="label lime">✅ 😊 MODEL</span>${example(v.sample)}<p>${v.note}</p></div><div class="comparison"><div class="card weak-card"><span class="label">❌ 🙁 AWKWARD</span>${example('“Thank you,” Ravi smiled.','plain')}<p>Smiled is an action, not a saying verb.</p></div><div class="card good-card"><span class="label lime">✅ 😊 CLEAR</span>${example('“Thank you,” Ravi said with a smile.')}<p>A saying verb tags the speech; the smile adds detail.</p></div></div>${note('<b>Choose one useful extra detail.</b> An action can show hesitation; an adverb can clarify how a line is spoken. Avoid contradictions such as “shouted softly”.')}`;}
function viewpoint(){const v=STUDIO.viewpoints[state.pov];return head('06 · VOICE & VIEWPOINT','Whose eyes are we looking through?','Changing the narrator changes what is noticed, understood and valued.')+tabs(STUDIO.viewpoints.map((p,i)=>[i,p.name]),'pov')+`<div class="card"><span class="label lime">${v.name.toUpperCase()}</span>${example(v.voice)}<p><b>Notices:</b> ${v.notices}</p><p><b>Limits of knowledge:</b> ${v.knows}</p><p><b>Writing opportunity:</b> ${v.change}</p></div>${note('<b>Keep the viewpoint steady.</b> First person uses I; a limited third-person story follows one character closely using he or she. Do not switch narrator halfway through by accident. Any viewpoint must still address the topic and use the chosen picture meaningfully.')}${quiz('pov',singleQuizzes.pov)}${scratch('pov-'+state.pov,'Retell a brief moment from this viewpoint. What can the narrator actually see, hear or know?','')}<h2>Avoid unexplained mind-reading</h2><div class="comparison"><div class="card"><h3>Knowledge the narrator cannot have</h3>${example('I watched Mr Tan. He secretly regretted every unkind word he had ever said.','plain')}</div><div class="card"><h3>Evidence the narrator can observe</h3>${example('Mr Tan looked down at the football. “I should not have shouted at you,” he said.')}<p>The words give the narrator evidence of his regret.</p></div></div>`;}
function flashback(){const f=STUDIO.flashbacks[state.flash];return head('07 · FLASHBACKS','Enter the memory. Return with purpose.','Use a flashback when the past helps the reader understand the current moment.')+tabs(STUDIO.flashbacks.map((p,i)=>[i,p.name]),'flash')+`<div class="card"><ol class="steps"><li><b>Open in the current scene.</b>${example(f.present)}</li><li><b>Use a trigger and make the time shift clear.</b>${example(f.enter)}</li><li><b>Develop the earlier incident.</b>${example(f.memory)}<p class="caption">This is the opening of the memory. Develop the important past events before returning.</p></li><li><b>Return with a voice, sound or action in the current scene.</b>${example(f.exit)}</li><li><b>Finish with an action that shows what has changed.</b>${example(f.end)}</li></ol></div>${note('<b>Tense control:</b> a past-tense story can begin the earlier memory with had, as in “Miss Tang had placed…”. Once the earlier time is clear, use simple past naturally. You do not need had in every sentence. Signal the return clearly; “the present” means the current story frame, not necessarily present tense.')}${quiz('flash',singleQuizzes.flash)}<h2>Flashback starter phrases</h2><p>Choose a phrase that fits your memory and make the time shift clear. Adapt the wording to your own scene.</p><div class="starter-grid">${STUDIO.flashbackStarters.map(group=>`<div class="card"><h3>${group.name}</h3><ul>${group.lines.map(line=>`<li>${esc(line)}</li>`).join('')}</ul></div>`).join('')}</div>${scratch('flashback','Write a flashback entry and a matching return. Use the same object, sound or place to connect them.','The sight of the empty bowl reminded me of the afternoon when I had first noticed Ethan beside the bin.\n\nA soft mew brought me back to the courtyard. Ethan was waiting by the gate, holding a fresh bowl of water.')}`;}
function conclusions(){const c=STUDIO.conclusions[state.ending],group=STUDIO.endingThemes[state.endingTheme];return head('08 · CONCLUSIONS','End the story with purpose.','Choose an ending that fits the conflict, the character and the exact topic.')+`<div class="grid">${STUDIO.conclusionTips.map(([title,description],i)=>`<div class="card"><span class="label blue">${i+1}</span><h3>${title}</h3><p>${description}</p></div>`).join('')}</div><h2>Six ways to conclude</h2><p>The same story about Alex and Whiskers can end in different ways. Each ending changes the meaning of what came before.</p>${tabs(STUDIO.conclusions.map((x,i)=>[i,x.name]),'ending')}<div class="card"><span class="label lime">✅ 😊 ${c.focus.toUpperCase()}</span><h2>${c.name}</h2><p>${c.summary}</p>${example(c.model)}<p><b>Why it works:</b> ${c.why}</p><p><b>Watch out:</b> ${c.watch}</p></div><div class="comparison"><div class="card weak-card"><span class="label">❌ 🙁 TOO GENERAL</span>${example('In the end, I learnt an important lesson and everything was fine.','plain')}<p>The problem, change and theme are vague.</p></div><div class="card good-card"><span class="label lime">✅ 😊 SPECIFIC</span>${example('Zack saw a gap near the front of the queue. He walked past it and joined the end.')}<p>His new behaviour shows what he has learnt about patience and consideration.</p></div></div>${note('<b>Choose with care:</b> a happy ending, a sad one or a twist can all work. Resolve the main story first; then leave the reader with one meaningful image, action or thought.')}<hr class="divider"><p class="eyebrow">FOR CONFIDENT WRITERS</p><h2>Quick bank: sayings that fit your theme</h2><p>Choose one at most. First show the important action; then let the saying echo its meaning.</p>${tabs(STUDIO.endingThemes.map((x,i)=>[i,x.name]),'endingTheme')}<div class="grid">${group.items.map(item=>`<div class="card"><span class="label ${item.kind==='Use with care'?'':'blue'}">${esc(item.kind.toUpperCase())}</span><h3>${esc(item.phrase)}</h3><p><b>Means:</b> ${esc(item.meaning)}</p>${example(item.model,item.kind==='Use with care'?'plain':'')}<p class="caption">${item.source?`Quotation verified by <a href="${item.url}" target="_blank" rel="noopener noreferrer">${item.source}</a>.`:'Adapt the idea to your own story.'}</p></div>`).join('')}</div><h2>How to quote correctly</h2><div class="grid">${[
['Use an idiom in your own sentence','No speech marks are needed when the idiom is part of your narration.','I had bitten off more than I could chew. I planned my week more carefully.'],
['Quote a saying in narration','Put the exact words in speech marks. This is a quotation, not spoken dialogue, so it does not need a speech tag.','The proverb “Actions speak louder than words” came to mind. I kept my promise.'],
['Tag words spoken aloud','Every line of direct speech needs a saying verb in this class. A statement followed by a tag takes a comma inside the speech marks.','“Actions speak louder than words,” Father reminded me.'],
['Name a real author accurately','Check the exact wording and attribution. Do not put your own paraphrase inside speech marks.','Helen Keller’s words returned to me: “Life is either a daring adventure or nothing.”']
].map(([title,tip,model])=>`<div class="card"><h3>✅ 😊 ${title}</h3><p>${tip}</p>${example(model)}</div>`).join('')}</div><div class="comparison"><div class="card weak-card"><span class="label">❌ 🙁 A SAYING THAT CLASHES</span>${example('Tim had changed completely. A leopard cannot change its spots.','plain')}<p>The proverb says the opposite of what the story has shown.</p></div><div class="card good-card"><span class="label lime">✅ 😊 A SAYING THAT FITS</span>${example('Tim had apologised and kept his promise. His actions mattered more than another apology.')}<p>The thought follows the evidence of change.</p></div></div>${note('<b>Quote check:</b> keep the exact wording, avoid uncertain author names, and use a full stop rather than joining two complete thoughts with a comma. Your own final action must still resolve the story.')}<p class="caption">The sayings often credited to Churchill beginning “Success is not final…” and “Courage is what it takes…” are <a href="https://winstonchurchill.org/resources/quotes/quotes-falsely-attributed/" target="_blank" rel="noopener noreferrer">not verified as his by the International Churchill Society</a>. This bank uses verified named quotations.</p>`;}
function checks(){return head('09 · FINAL CHECKS','Finish with care.','Check the meaning first, then the sentences and punctuation.')+`<h2>Our classroom conventions</h2><p class="caption">These are the writing expectations for this class. Some are style choices rather than rules for every kind of English writing.</p><div class="grid">${[
['Sound words','Crash! The bowl hit the floor.','No speech marks for a sound in narration. If a character actually says “Ouch!” or “Help!”, those spoken words use speech marks.'],
['Use full words','examination · refrigerator · photograph','Use examination instead of exam and refrigerator instead of fridge in your composition, following the class expectation.'],
['Family names','Mother waited outside.\n“Dad, may I help?” I asked.','Reserve Mum and Dad for direct speech. Use Mother or Father as names in narration; write my mother or my father with lower-case letters after my.'],
['Introduce short forms','We travelled on the Mass Rapid Transit (MRT) system.','Spell out the term first and put the short form in brackets. Use MRT afterwards if needed. Avoid unexplained abbreviations.'],
['British spelling','colour · favourite · realised · apologised · centre','Practise is the verb: I practise writing. Practice is the noun: This practice helps. Use travelling, grey and behaviour.'],
['New speaker, new paragraph','“May I help?” Ethan asked.\n\n“Yes, please,” Jayden replied.','Start a new paragraph when the speaker changes. Keep the speaker’s related action with the correct speech.']
].map(([t,e,d])=>`<div class="card"><h3>${t}</h3>${example(e)}<p>${d}</p></div>`).join('')}</div><h2>Your final read-through</h2><p id="check-count" class="score">${state.checks.size} of ${STUDIO.checklist.length} checks complete</p><div class="meter" aria-hidden="true"><span id="check-meter" style="width:${state.checks.size/STUDIO.checklist.length*100}%"></span></div><ul class="checklist">${STUDIO.checklist.map((c,i)=>`<li><label><input type="checkbox" data-check="${i}" ${state.checks.has(i)?'checked':''}><span>${c}</span></label></li>`).join('')}</ul><div class="actions"><button class="secondary" id="reset-checks">Clear these ticks</button><button class="primary" data-print>Print this checklist</button></div>${note('<b>Use your final minutes purposefully:</b> check missing words, tense changes, full stops, speech marks and speaker changes. Clear, accurate writing matters more than adding one last difficult word.')}`;}
function render(keepScroll=false){const route=location.hash.slice(1)||'start';const views={start,themes,craft,speech,verbs,plot,viewpoint,flashback,conclusions,check:checks};main.innerHTML=(views[route]||start)()+`<a class="back-top" href="#start">Back to the writing desk</a>`;document.querySelectorAll('nav a').forEach(a=>{if(a.dataset.section===(views[route]?route:'start'))a.setAttribute('aria-current','page');else a.removeAttribute('aria-current')});document.title=`${(sections.find(x=>x[0]===route)||sections[0])[1]} · Ms H’s Writing Studio`;if(!keepScroll)window.scrollTo({top:0,behavior:'instant'});}
function normalise(s){return s.trim().replace(/[“”]/g,'"').replace(/[‘’]/g,"'").replace(/\s+/g,' ').replace(/\s+([,?.!])/g,'$1');}
main.addEventListener('input',e=>{if(e.target.dataset.draft)state.drafts[e.target.dataset.draft]=e.target.value;});
main.addEventListener('change',e=>{if(e.target.dataset.builder){state.builder[e.target.dataset.builder]=e.target.value;document.querySelector('#builder-result').innerHTML=builderOutput();}if(e.target.dataset.check!==undefined){const i=Number(e.target.dataset.check);e.target.checked?state.checks.add(i):state.checks.delete(i);document.querySelector('#check-count').textContent=`${state.checks.size} of ${STUDIO.checklist.length} checks complete`;document.querySelector('#check-meter').style.width=`${state.checks.size/STUDIO.checklist.length*100}%`;}});
main.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;
 if(b.dataset.pick){const key=b.dataset.pick,value=b.dataset.value;state[key]=['theme','emotion','sense','verb','plot','pov','flash','ending','endingTheme','rep'].includes(key)?Number(value):value;render(true);main.querySelector(`[data-pick="${key}"][data-value="${value}"]`)?.focus({preventScroll:true});}
 if(b.dataset.answer){const id=b.dataset.answer;const q=id.startsWith('speech-')?STUDIO.speechQuiz[Number(id.split('-')[1])]:singleQuizzes[id];const choice=Number(b.dataset.choice);state.answers[id]=choice;const box=b.closest('.quiz');box.querySelectorAll('.option').forEach((o,i)=>{o.classList.toggle('correct',i===choice&&choice===q.a);o.classList.toggle('wrong',i===choice&&choice!==q.a);o.setAttribute('aria-pressed',String(i===choice));});const f=box.querySelector('.feedback');f.className='feedback '+(choice===q.a?'good':'bad');f.textContent=choice===q.a?'Yes — that works. '+q.why:'Look again. Read the rule and try another choice.';const score=document.querySelector('#speech-score');if(score)score.textContent=speechScore();}
 if(b.id==='reset-quiz'){Object.keys(state.answers).filter(k=>k.startsWith('speech-')).forEach(k=>delete state.answers[k]);render(true);}
 if(b.id==='check-repair'||b.id==='show-repair'){const r=STUDIO.repairs[state.rep],f=document.querySelector('#repair-feedback');const input=document.querySelector('#repair-input').value;const right=r.answers.some(a=>normalise(a)===normalise(input));f.className='feedback '+(b.id==='check-repair'&&right?'good':'');if(b.id==='show-repair')f.innerHTML=`<b>Suggested repair</b>${example(r.answers[0])}<p>${r.why}</p>`;else f.textContent=!input.trim()?'Type a corrected sentence first.':right?'That repair works. '+r.why:'This does not match a suggested repair yet. Check punctuation and capital letters, or reveal a suggested repair. Other grammatical rewrites are possible.';}
 if(b.dataset.paragraph){const f=document.querySelector('#paragraph-feedback');f.textContent=b.dataset.paragraph==='3'?'Correct. Marcus speaks, then Zane, then Marcus again: three speaker paragraphs.':'Count the speaker changes, not just the number of characters. Marcus → Zane → Marcus needs three paragraphs.';f.className='feedback '+(b.dataset.paragraph==='3'?'good':'bad');}
 if(b.id==='reset-checks'){state.checks.clear();render(true);}
 if(b.hasAttribute('data-print'))window.print();
});
window.addEventListener('hashchange',()=>{render();main.focus({preventScroll:true});});render();
// Optional browser-native tools share the same validated state as the visible controls.
if(document.modelContext?.registerTool){
 const lifecycle=new AbortController();
 const register=tool=>{try{Promise.resolve(document.modelContext.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch{}};
 register({name:'configure_speech_example',title:'Configure the speech example',description:'Choose speaker, tag position, sentence kind and detail for the visible direct-speech builder. Changes only the current tab.',inputSchema:{type:'object',properties:{speaker:{type:'string',enum:['Tom','he','Ethan','she','I']},position:{type:'string',enum:['front','back']},kind:{type:'string',enum:['statement','question','exclamation']},style:{type:'string',enum:['plain','adverb','action','both']}},required:['speaker','position','kind','style'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input){const allowed={speaker:['Tom','he','Ethan','she','I'],position:['front','back'],kind:['statement','question','exclamation'],style:['plain','adverb','action','both']};if(!input||typeof input!=='object'||Object.keys(input).length!==4||Object.entries(allowed).some(([k,v])=>!v.includes(input[k])))throw new Error('Choose one supported value for each of the four fields.');state.builder={...input};state.speech='build';location.hash='speech';render();return {sentence:makeSpeech(state.builder),section:'Direct speech lab',activity:'Build a sentence'};}});
}
