const STUDIO = {
  themes: [
    {id:'responsibility',title:'Responsibility & honesty',tag:'CORE FAMILY',question:'What difficult choice does the character make, and what does putting things right involve?',story:'Tom and the examination',before:'Tom wants to prove that Mother’s patient help has paid off. When he cannot solve the questions, John’s answers become a temptation.',turn:'Miss Tang gives him a chance to explain. Tom notices Mother’s note and chooses to confess instead of inventing another excuse.',after:'The consequences remain. Tom asks for help and works honestly; a later, modest improvement belongs to him.',adapt:[['Being honest','Develop the temptation, the concealment and the decision to tell the truth.'],['Taking responsibility','Give enough space to accepting the consequences and making amends.'],['A difficult decision','Make both options and their costs clear before the choice.'],['A change for the better','Show changed behaviour when a similar temptation returns.']],trap:'Being caught is an event. Choosing to tell the truth is a turning point. An apology alone does not prove responsibility.',prompt:'A borrowed item is damaged. Plan a choice, a confession and a realistic way to make amends.'},
    {id:'challenge',title:'Challenge & courage',tag:'CORE FAMILY',question:'What makes the task hard for this particular character?',story:'The tournament setback',before:'A missed pass leaves the team behind. The player wants to avoid the ball after the mistake.',turn:'Instead of hiding, the player calls for the next pass and uses the advice practised during training.',after:'The team may still lose. The character’s response to pressure shows growth.',adapt:[['Overcoming a challenge','Name the obstacle and show a changed approach.'],['Showing courage','Establish fear, then show action despite it.'],['Perseverance','Show another attempt that uses what the character has learnt.'],['Sportsmanship','Develop what the character does for an opponent, especially when disappointed.']],trap:'Winning does not automatically demonstrate courage. Let the reader see the fear and the decision.',prompt:'A pupil is afraid to speak during a presentation. What manageable step helps the pupil continue?'},
    {id:'kindness',title:'Kindness & consideration',tag:'CORE FAMILY',question:'Who needs help, and what does the helper notice or give up?',story:'Zack in the canteen queue',before:'Zack treats everyone ahead of him as an obstacle. His impatience causes a younger pupil’s meal to fall.',turn:'He sees the younger pupil’s trembling lip and recognises the harm he has caused.',after:'He replaces the meal, waits his turn and helps another pupil retrieve dropped coins.',adapt:[['Being considerate','Show the character noticing another person’s needs.'],['Helping someone','Develop purposeful help and its effect.'],['Making a sacrifice','Establish what the helper values and chooses to give up.'],['Being thankful','Shift the focus to the person who receives help and expresses appreciation meaningfully.']],trap:'A kind act can start the story, but a thankfulness topic needs a developed response from the grateful person.',prompt:'Someone needs help just as you are about to join an activity you have been looking forward to.'},
    {id:'friendship',title:'Unexpected friendship',tag:'FAMILIAR CLASS LESSON',question:'Why would these two characters normally not become friends?',story:'Ethan, Jayden and the cat',before:'Jayden assumes that quiet Ethan is unfriendly. He has never tried to understand him.',turn:'He sees Ethan caring for a frightened stray cat and discovers a considerate side to him.',after:'They speak while waiting for an adult to help. Their friendship develops through later meetings and shared care.',adapt:[['A misunderstanding','Establish the mistaken belief, the evidence that corrects it and the response.'],['An unexpected friendship','Make the friendship unlikely at first and believable by the end.'],['Looking beyond first impressions','Show exactly what changes the character’s judgement.'],['Teamwork','Show each person’s contribution and how cooperation helps.']],trap:'One conversation does not have to produce instant best friends. Allow trust to grow.',prompt:'Marcus dismisses Zane as the class clown. A problem with their project reveals Zane’s useful skills. Plan a believable change in their relationship.'},
    {id:'disappointment',title:'Patience & disappointment',tag:'BROADEN YOUR COVERAGE',question:'What was the character hoping for, and how does the character respond when it does not happen?',story:'Zack chooses to wait',before:'Zack expects to buy his favourite meal and resents the long queue.',turn:'After seeing the consequences of pushing forwards, he turns down an invitation to cut the queue again.',after:'His favourite dish has sold out. He accepts another meal without taking his frustration out on others.',adapt:[['A long wait','Make the waiting affect choices and emotions.'],['Dealing with disappointment','Establish the hope before the setback.'],['Being patient','Show restraint while waiting is still difficult.'],['An unexpected outcome','Create a clear expectation before the outcome changes.']],trap:'Do not solve every disappointment with a convenient prize. The response can be the meaningful ending.',prompt:'Rain causes a much-anticipated activity to be cancelled. What does the character do next?'},
    {id:'surprise',title:'Surprises, gifts & celebrations',tag:'BROADEN YOUR COVERAGE',question:'Why does this event or object matter to the character?',story:'A thank-you for Mr Tan',before:'A child once avoided Mr Tan, the neighbour who complained about footballs landing in his garden.',turn:'After discovering their shared love of football, the child plans a small thank-you with the neighbours.',after:'Mr Tan recognises the effort behind the gift. The ending shows how the relationship has changed.',adapt:[['A special gift','Explain the personal significance, not just the price or appearance.'],['A secret','Show why it is kept and how keeping or revealing it affects events.'],['Celebration','Develop the occasion and what people do to mark it.'],['A pleasant surprise','Establish what the character expects before the reveal.']],trap:'A party described in detail still needs a clear connection to the exact topic.',prompt:'A small, handmade gift means more to its recipient than the giver expected.'}
  ],
  senses: [
    ['Sight','What would this character notice?','Grey smudges spread across Tom’s examination paper. The answer space remained empty.','The detail makes his struggle visible.'],
    ['Sound','What sound changes the atmosphere?','Chairs scraped against the floor and coins clinked against the canteen counters.','Specific sounds establish the busy setting.'],
    ['Smell','What smell draws attention?','The aroma of fried noodles drifted from the stall, making Zack glance towards the queue again.','The smell connects to his hunger and impatience.'],
    ['Touch','What does the body feel?','The wet umbrella handle slipped in my palm as I reached towards Mr Tan’s fallen bag.','The sensation develops the rainy scene and the action.'],
    ['Taste','Does taste belong in this moment?','The plain bun tasted dry, but Zack finished it without complaining.','Taste supports the contrast between his hoped-for meal and his changed response.']
  ],
  emotions: [
    ['Fear','I was afraid.','My cold, clammy hands tightened around the railing. I wanted to step forwards, but my feet would not move.','Body + action show hesitation. Choose a response that fits the actual danger.'],
    ['Shock','She was shocked.','Maya stood rooted to the spot, her mouth agape. Her eyes moved from the broken model to the glue still in my hand.','A familiar expression becomes more precise when it connects to the cause.'],
    ['Happiness','She was happy.','Siti grinned from ear to ear and clapped her hands when the teacher announced the result.','Face + action connect the feeling to an event.'],
    ['Sadness','He was sad.','Kai’s head hung low. His lower lip trembled as he folded the unused invitation and slipped it into his bag.','An object and an action give the emotion a reason.'],
    ['Relief','I felt relieved.','I released the breath I had been holding. Father lifted my missing school bag, and the tightness in my chest began to ease.','A change in the body shows that the worry is ending.'],
    ['Guilt','Tom felt guilty.','Tom stared at Mother’s note. He opened his mouth to speak, then lowered his eyes to the answers he had copied.','Attention, silence and avoidance reveal the conflict.'],
    ['Anger','Zack was angry.','Zack’s jaw tightened. He gripped the edge of the tray and answered Jason through clenched teeth.','Controlled details often work better than several extreme comparisons.'],
    ['Pain','My ankle hurt.','Pain shot through my ankle as I tried to stand. I gritted my teeth and lowered myself onto the bench.','The reaction follows the movement that causes pain.']
  ],
  verbs: [
    {name:'Calm & reassuring',words:['said','replied','explained','assured','reassured'],sample:'“We can ask for help,” Ethan said calmly, keeping his distance from the frightened cat.',note:'Said is useful. Assured and reassured usually need a person: he reassured me; she assured Tom.'},
    {name:'Happy & excited',words:['exclaimed','cheered','announced','cried'],sample:'“We finished it!” Zane exclaimed, lifting his hands from the keyboard.',note:'Announced tells us how the news is delivered; the context must establish the happiness.'},
    {name:'Angry & frustrated',words:['snapped','retorted','protested','demanded','complained'],sample:'“I was here first,” Zack snapped, tightening his grip on the tray.',note:'Retorted means answered sharply. Use it as a response, not as the first line of a conversation.'},
    {name:'Afraid & anxious',words:['whispered','stammered','pleaded','cried'],sample:'“Please wait for me,” the younger boy pleaded, clutching the strap of his bag.',note:'Match the volume to the setting. Whispered is quiet; cried can mean called out.'},
    {name:'Sad & distressed',words:['murmured','sobbed','whispered','lamented'],sample:'“I thought you had forgotten,” Ravi murmured, studying the folded invitation.',note:'Sobbed suits speech broken by crying. Avoid making a sobbing character deliver a long, polished speech.'},
    {name:'Surprised & confused',words:['asked','exclaimed','blurted','stammered'],sample:'“You play football?” I asked, staring at the trophies on Mr Tan’s shelf.',note:'A question mark belongs to a question. Asked is often more precise than an elaborate alternative.'},
    {name:'Sorry & hesitant',words:['admitted','confessed','apologised','murmured'],sample:'“I copied John’s work,” Tom confessed, forcing himself to meet Miss Tang’s eyes.',note:'Confessed implies acknowledging wrongdoing. Admitted can acknowledge an uncomfortable fact.'},
    {name:'Firm & determined',words:['insisted','declared','urged','promised'],sample:'“Let us try once more,” Marcus urged, sliding the laptop towards Zane.',note:'A verb can fit more than one emotion. Choose the meaning first, then add an action or adverb if it helps.'}
  ],
  speechRules: [
    ['Tag at the front','Miss Tang said, “You may begin.”','Put a comma after the speech tag. Begin the spoken sentence with a capital letter. Its final punctuation stays inside the closing speech marks.'],
    ['Tag at the back: name','“I copied John’s work,” Tom confessed.','Use a comma inside the closing speech marks for a statement followed by a speech tag. Tom remains capitalised because it is a name.'],
    ['Tag at the back: pronoun','“I copied John’s work,” he confessed.','He becomes he because the speech and its tag form one sentence. The full stop comes after the tag. The pronoun I always stays capitalised.'],
    ['Question + tag','“Did you copy this?” she asked.','Keep the question mark inside the speech marks. Do not add a comma after it. A following pronoun such as he or she still begins with a lower-case letter; I stays capitalised.'],
    ['Exclamation + tag','“Stop pushing!” Jason shouted.','Keep the exclamation mark inside the speech marks. Do not add a second comma. Jason keeps its capital letter because it is a name.'],
    ['An action is its own sentence','“I will wait.” Zack stepped to the back of the queue.','Stepped is an action, not a saying verb. End the spoken sentence with a full stop and begin the action sentence with a capital letter.'],
    ['One spoken sentence, interrupted','“If you need help,” Ethan said, “we can ask an adult.”','The tag interrupts one sentence. Use commas around the tag and continue with a lower-case letter, unless the next word needs a capital letter of its own.'],
    ['Two spoken sentences, one speaker','“I am sorry,” Zack said. “I will replace your meal.”','The first spoken sentence ends with its tag. The next spoken sentence begins with a capital letter. Keep the same speaker’s speech together when it belongs to the same paragraph.']
  ],
  speechQuiz: [
    {q:'Choose the correctly punctuated statement with a pronoun tag.',options:['“I will wait.” he said.','“I will wait,” he said.','“I will wait,” He said.'],a:1,why:'The statement and he said form one sentence. Use a comma inside the speech marks and a lower-case h.'},
    {q:'Choose the correct question with a name tag.',options:['“Can you help?” Ethan asked.','“Can you help?,” Ethan asked.','“Can you help,” Ethan asked?'],a:0,why:'The question mark belongs inside the speech marks. Ethan keeps the capital E because it is a name.'},
    {q:'Choose the correct tag at the front.',options:['Miss Tang said “You may begin”.','Miss Tang said, “you may begin.”','Miss Tang said, “You may begin.”'],a:2,why:'Put a comma after said, capitalise You, and put the full stop inside the closing speech marks.'},
    {q:'Choose the correct punctuation for an action beat.',options:['“I am sorry,” Tom lowered his eyes.','“I am sorry.” Tom lowered his eyes.','“I am sorry.” tom lowered his eyes.'],a:1,why:'Lowered his eyes is an action, not a speech tag. It begins a new sentence.'},
    {q:'Choose the correct exclamation with a pronoun tag.',options:['“Look out!” she cried.','“Look out!”, she cried.','“Look out!” She cried.'],a:0,why:'The exclamation mark replaces the comma. The following speech tag continues the sentence, so she begins with a lower-case s.'},
    {q:'Choose the correct interrupted sentence.',options:['“If it rains,” he said. “we will wait.”','“If it rains,” he said, “We will wait.”','“If it rains,” he said, “we will wait.”'],a:2,why:'The whole spoken sentence is If it rains, we will wait. The second part continues that sentence, so we stays lower case.'},
    {q:'Which revision makes a smile work as an action?',options:['“Thank you,” Ravi smiled.','“Thank you.” Ravi smiled.','“Thank you.” ravi smiled.'],a:1,why:'For our classroom convention, smiled is an action, not a saying verb. Alternatively: “Thank you,” Ravi said with a smile.'},
    {q:'Which version follows the class rule for a sound in narration?',options:['“Crash!” The bowl struck the floor.','Crash! The bowl struck the floor.','“Crash!” said the bowl.'],a:1,why:'Crash represents a sound in the scene, not spoken words. Leave out the speech marks.'},
    {q:'Which sentence uses an emotion verb naturally?',options:['“Why did you do that?” she demanded softly and loudly.','“I can help,” he grinned.','“I was here first,” Zack retorted.'],a:2,why:'Retorted is a saying verb that suits a sharp response. Avoid contradictory adverbs and do not use grinned as a saying verb.'},
    {q:'Which sentence follows the classroom rule for family names in narration?',options:['Mum placed the book on the table.','Mother placed the book on the table.','mother placed the book on the table.'],a:1,why:'In this class, use Mother or Father as names in narration. Reserve Mum and Dad for direct speech. With my, write my mother or my father.'},
    {q:'Choose the correct pronoun after a question.',options:['“Are you ready?” I asked.','“Are you ready?” i asked.','“Are you ready?,” I asked.'],a:0,why:'The pronoun I always has a capital letter, even when the tag follows the speech.'},
    {q:'Choose the correctly punctuated action added to a speech tag.',options:['“I can help,” Ethan said, kneeling beside the box.','“I can help.” Ethan said, kneeling beside the box.','“I can help,” Ethan said kneeling, beside the box.'],a:0,why:'Said is the saying verb. The comma after said introduces the accompanying action.'}
  ],
  repairs: [
    {raw:'“I will replace your meal.” he said.',answers:['“I will replace your meal,” he said.'],why:'Change the full stop inside the speech marks to a comma. The tag continues the same sentence.'},
    {raw:'“Are you all right?” He asked.',answers:['“Are you all right?” he asked.'],why:'Keep the question mark. Change He to he because the tag is part of the same sentence.'},
    {raw:'Zane replied “I saved a copy.”',answers:['Zane replied, “I saved a copy.”'],why:'The speech tag comes first, so add a comma after replied.'},
    {raw:'“Thank you,” she smiled.',answers:['“Thank you.” She smiled.','“Thank you,” she said with a smile.','“Thank you,” she said, smiling.'],why:'Smiled is an action. Make it a separate sentence, or add a real saying verb such as said.'},
    {raw:'“I can help!” ethan exclaimed.',answers:['“I can help!” Ethan exclaimed.'],why:'A name keeps its capital letter, even when the speech tag comes at the back.'},
    {raw:'“If you wait,” she said, “We can go together.”',answers:['“If you wait,” she said, “we can go together.”'],why:'The second part continues the same spoken sentence. Use a lower-case w.'}
  ],
  plots: [
    {name:'A physical fight',kind:'External conflict',spark:'An accusation after a damaged project leads to a shove.',build:'One pupil stumbles against a desk. A chair scrapes across the floor. Another pupil steps back, realising that the argument has become dangerous.',moment:'His fist tightened. Across the desk, he saw his classmate flinch. He could strike back—or stop.',choice:'He lowers his hand and moves away while a classmate calls a teacher.',after:'The pupils face consequences, explain what happened and repair the damage. An apology does not make every feeling disappear at once.',avoid:'Do not turn the scene into a long action film or make violence earn admiration. Develop cause, reaction and consequence.',question:'How can the decision to stop reveal more character than another punch?'},
    {name:'A quarrel',kind:'External conflict',spark:'Marcus thinks Zane has failed to complete his part of the project.',build:'“You never take anything seriously,” Marcus snapped, pulling the laptop towards himself. Zane’s reply stopped halfway out of his mouth.',moment:'Marcus notices a folder of completed drawings on Zane’s screen. His accusation no longer fits the evidence.',choice:'He asks what happened, listens and acknowledges that he judged too quickly.',after:'They agree on responsibilities and show a gradual change in how they speak to each other.',avoid:'Do not write pages of shouting with no action or new information. Each exchange should change the situation.',question:'What does each character believe, and which detail exposes the misunderstanding?'},
    {name:'A dilemma',kind:'Two difficult options',spark:'A pupil must choose between two activities held at the same time: a tournament and an eagerly awaited family outing.',build:'The team has practised for weeks, but the pupil has also looked forward to spending time with a parent who often works late.',moment:'She looked from the team message to the tickets on the table. Whichever she chose, she would miss something important.',choice:'She discusses the clash and makes a decision rather than waiting for the problem to vanish.',after:'She accepts the cost of the choice and communicates it respectfully.',avoid:'A dilemma needs two meaningful alternatives. The choice is not automatically about right and wrong.',question:'What is gained and lost with each option?'},
    {name:'A moral dilemma',kind:'Values, duty or temptation',spark:'Tom sees answers he could copy. He wants a better mark, but he knows the work is not his.',build:'His gaze moves from the blank answer space to John’s paper. He tells himself that one copied answer will not matter.',moment:'Later, an excuse forms when Miss Tang asks him to explain. Mother’s note reminds him of the trust at stake.',choice:'He confesses despite knowing that he will still face consequences.',after:'He accepts the consequences and changes the way he works. His next result is modest but honest.',avoid:'Show the pressure behind the wrong choice without pretending it is justified. Some moral dilemmas also involve competing duties, such as loyalty and fairness.',question:'Which value is at stake, and what makes doing the right thing difficult?'},
    {name:'A fire',kind:'An urgent danger',spark:'During an activity, the character notices smoke and hears the alarm.',build:'The sharp smell interrupted our conversation. Beyond the doorway, a thin grey haze blurred the far wall.',moment:'My project was still on the table. I took a step towards it, then heard the teacher directing us to the exit.',choice:'The character leaves the belongings behind and follows the adult’s evacuation instructions.',after:'From a safe place, the character explains what was noticed. Trained responders deal with the fire.',avoid:'Keep the scene credible. A child should not run back into a burning building, fight the fire or perform a miraculous rescue.',question:'How can a safe, difficult choice show courage or responsibility?'}
  ],
  viewpoints: [
    {name:'The child',voice:'I used to hurry past Mr Tan’s gate. That afternoon, I stopped when his shopping bag split and oranges rolled across the wet pavement.',notices:'The rain, the scattered oranges and a chance to help someone previously avoided.',knows:'The child can describe Mr Tan’s expression and words, but cannot know his private thoughts.',change:'The child starts to question a first impression.'},
    {name:'An elderly person',voice:'My fingers tightened around the torn handle. Before I could bend down, the boy from next door crouched beside the drain and caught the last orange.',notices:'A familiar neighbour, the awkward bag and the boy’s unexpected kindness.',knows:'Mr Tan knows his own memories and intentions. He does not know what the boy thinks unless the boy shows or tells him.',change:'The older narrator can offer help, knowledge and friendship too. Age alone does not make a character helpless.'},
    {name:'An adult',voice:'I watched my son stop beside Mr Tan. Usually, I had to remind him to slow down. Today, he was the one asking us to wait.',notices:'The child’s behaviour compared with earlier habits.',knows:'A parent can remember earlier incidents but cannot read the child’s mind.',change:'The adult’s surprise reveals the child’s growth without a long moral speech.'},
    {name:'A younger child',voice:'An orange rolled towards the drain. I put my shoe in its way. Mr Tan smiled at me, and I held it out with both hands.',notices:'A small, concrete detail close to the child’s own experience.',knows:'Use limited knowledge and a believable concern. Keep the language grammatical; a young viewpoint does not require baby talk.',change:'A small action can still contribute meaningfully.'},
    {name:'An animal',voice:'I crouched beneath the bench as shoes splashed past. Then the boy knelt. He set a bowl nearby and moved back. I sniffed the air before edging forwards.',notices:'Movement, distance, sound, smell and physical comfort.',knows:'Keep an ordinary animal’s knowledge consistent. It would not normally know an examination timetable or understand every human conversation.',change:'Fear can become trust through repeated actions. Use personification consistently if the story deliberately gives the animal human abilities.'}
  ],
  flashbacks: [
    {name:'An object',present:'I turned the examination paper over. The mark was modest, but this time every answer was mine.',enter:'The small note beneath my pencil case took me back to the afternoon when I had copied John’s work.',memory:'Miss Tang had placed the two papers side by side. I stared at the matching error and searched for an excuse.',exit:'“Tom, are you ready to go?” Mother’s voice brought me back to the present.',end:'I placed the paper in her hand. This time, I had nothing to hide.'},
    {name:'A sound',present:'A sharp blast of the whistle signalled the start of training. I tightened my grip on the hockey stick.',enter:'The sound reminded me of our last tournament, when one careless pass had cost us possession.',memory:'My teammates had been waiting for me to move. Instead, I had stood still, afraid of making another mistake.',exit:'“Your turn,” Ryan called. I looked up and stepped onto the pitch.',end:'The ball came towards me. I called for support and moved to meet it.'},
    {name:'A place',present:'I paused beside the canteen queue. A younger pupil was counting coins in his palm.',enter:'The sight brought back the day when my impatience had sent Ravi’s lunch crashing to the floor.',memory:'I had wanted to save a few minutes. Instead, I had left another pupil staring at his ruined meal.',exit:'A coin rolled against my shoe. I blinked and looked down at the pupil beside me.',end:'“Take your time,” I said, handing it back. Then I waited for my turn.'}
  ],
  checklist: [
    'My story answers the exact topic, not just a related idea.',
    'At least one chosen picture contributes meaningfully to the story.',
    'The complication has a clear cause and believable consequences.',
    'The turning point changes a choice, understanding or relationship.',
    'I have developed the important moment with selected actions, thoughts and sensory details.',
    'My character’s change is shown through behaviour.',
    'My viewpoint stays consistent; I do not suddenly read another character’s mind.',
    'My tense and any flashback transitions are clear.',
    'My speech marks, commas, question marks and full stops are in the right places.',
    'I begin a new paragraph when a different person speaks.',
    'My action beats are not incorrectly joined to speech with a comma.',
    'I use complete forms such as examination and refrigerator.',
    'Mum and Dad appear only in direct speech, following our class convention.',
    'I spell out an abbreviation in full before introducing its short form.',
    'Sound words in narration have no speech marks.',
    'I have checked British spelling, sentence boundaries and subject–verb agreement.',
    'My ending resolves the main issue and connects to the topic.'
  ]
};
